name: CI / CD for Web BFF Lamdda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Installs requirements
        run: pip install -r requirements.txt
      - name: Linting
        run: flake8 .
      - name: Tests
        run: PYTHONPATH=$PWD/src pytest . --cov=src
